### ISSUE TITLE
CalendarEventDevice is deprecated

### ISSUE THREAD

**Issue by gateriderz** [gadgetchnnel/entities_calendar#12]
Received an early release warning of deprecated attribute.

Home Assistant Core 2022.5.0b3

`CalendarEventDevice is deprecated, modify EntitiesCalendarDevice to extend CalendarEntity`

Let me know if you need more details.

Thank you

**Comment by gadgetchnnel** [comment]
I have refactored this in the latest beta version, 0.0.9b0, can you please try updating to this and see if this works for you.

**Comment by gateriderz** [comment]
Tested this version and its working, no warnings.

Thank you
