### ISSUE TITLE
Manifest file for custom integration

### ISSUE THREAD

**Issue by thomas-peuziat** [gadgetchnnel/entities_calendar#6]
Since Home Assistant version 2021.3, custom integrations now require a `version` key in the manifest file, as you can see here : 

- [HA 2021.3 release note](https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes), 
- [Doc about creating an integration manifest](https://developers.home-assistant.io/docs/creating_integration_manifest/).

For now, it only create a warning at startup, but it will eventually be blocked from loading.

```
[homeassistant.loader] No 'version' key in the manifest file for custom integration 'entities_calendar'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'entities_calendar'
```

**Comment by gadgetchnnel** [comment]
Thanks, I've added this in version 0.0.7
